services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${SPRING_PORT}"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI}
      - HYPERMANAGER_API_BASE_URL=${HYPERMANAGER_BASE_URL}
      - HYPERMANAGER_API_API_KEY=${HYPERMANAGER_API_KEY}
    depends_on:
      - mongo
  mongo:
    image: ${MONGO_IMAGE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}

volumes:
  mongo-data:
